version: '3'

services:
    web:
        image: nginx:latest
        ports:
            - "8088:80"
        volumes:
            - ./code:/code
            - ./conf:/etc/nginx/conf.d
            - ./log:/var/log/nginx
            - "phpsocket:/var/run"

    php:
        image: php:fpm
        volumes:
            - ./code:/code
            - ./fpm/etc:/usr/local/etc
            - ./fpm/etc:/usr/local/etc/php-fpm.d
            - ./zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
            - "phpsocket:/var/run"

volumes:
    phpsocket: