# 当前的版本 
version: "3"
# 待安装的镜像
services:

  activemq:
    image: webcenter/activemq
    container_name: activemq
    #reboot 后会随机启动
    restart: always
    #容器的映射端口
    ports:
      - "61616:61616"
      - "8161:8161"
    restart: always
    # 限制日志的大小
    logging: 
        driver: "json-file"
        options: 
            max-size: "500m"
    #定义挂载点
    volumes:
      - ./data/activemq:/data/activemq
