version: '3'
services:
 tracker:
  container_name: tracker
  image: "morunchang/fastdfs"
  # 该容器是否需要开机启动+自动重启。若需要，则取消注释。
  restart: always
  network_mode: host
  entrypoint: sh tracker.sh
 storage0:
  container_name: storage0
  depends_on:
    - tracker
  build: ./storage
  # 该容器是否需要开机启动+自动重启。若需要，则取消注释。
  restart: always
  # 把root权限带进去
  privileged: true
  network_mode: host
  environment:
   GROUP_NAME: storagegroup
   TRACKER_IP: 120.27.229.28:22122
  ports:
    - "8080:8080"
    - "23000:23000"
  # 数据卷挂载目录
  volumes:
    - /var/local/docker/fastdfs/storage0:/data/fast_data