version: '3'
services:
  fastdfs:
    build: .
    image: qbanxiaoli/fastdfs
    # 该容器是否需要开机启动+自动重启。若需要，则取消注释。
    restart: always
    # 限制日志的大小
    logging: 
        driver: "json-file"
        options: 
            max-size: "500m"
    container_name: fastdfs
    ports:
      - 80:8080
      - 22122:22122
      - 23000:23000
    environment:
      # 使用东八区的时间
      TZ: Asia/Shanghai
      # nginx服务端口,默认8080端口，可修改
      WEB_PORT: 8080
      # tracker_server服务端口，默认22122端口，可修改
      FDFS_PORT: 22122
      # fastdht服务端口，默认11411端口，可修改
      FDHT_PORT: 11411
      # docker所在主机的IP地址，默认使用eth0网卡的地址
      IP: 120.27.229.28
    volumes:
      # 将本地目录映射到docker容器内的fastdfs数据存储目录，将fastdfs文件存储到主机上，以免每次重建docker容器，之前存储的文件就丢失了。
      - ~/fastdfs:/var/local
    # 网络模式为host，可不暴露端口，即直接使用宿主机的网络接口，只适用于linux系统
    # network_mode: host
    networks:
      fastdfs_net:
        ipv4_address: 120.27.229.28

# fastdfs专用网络，由于windows和unix识别不了host网络，目前需要新建网段，强制指定容器ip跟宿主机ip一致
networks:
  fastdfs_net:
    driver: bridge
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: 120.27.229.0/24
