version: "3"
services:
    jenkins:
        container_name: jenkins
        image: jenkins
        restart: always
        volumes:
            - ./jenkins_home:/var/jenkins_home
        ports:
            - "8090:8080"