tomcat:
    container_name: tomcat
    restart: always
    image: tomcat:9.0
    ports:
      - 8080:8080
      - 8009:8009
    volumes:
      - ./webapps/solo.war:/usr/local/tomcat/webapps/solo.war
      - ./conf/server.xml:/usr/local/tomcat/conf/server.xml
      - ./logs:/usr/local/tomcat/logs