tomcat:
    container_name: tomcat
    # 该容器是否需要开机启动+自动重启。若需要，则取消注释。
    restart: always
    image: tomcat:9.0
    ports:
      - 8080:8080
      - 8009:8009
    volumes:
      - ./webapps:/usr/local/tomcat/webapps/
      - ./conf:/usr/local/tomcat/conf/
      - ./logs:/usr/local/tomcat/logs